### ISSUE TITLE
HTTPS issues

### ISSUE THREAD

**Issue by rodber** [xrdebug/xrdebug#44]
When passing `-c` I'm getting the following errors when using cert files.

`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.
`chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
`cert.pem`     : will break many server configurations, and should not be used
                 without reading further documentation (see link below).

https://eff-certbot.readthedocs.io/en/latest/using.html#where-are-my-certificates

```plain
RuntimeException: Connection from tcp://172.71.238.114:48150 failed during TLS handshake: Unable to set private key file `/etc/letsencrypt/archive/merge.xrdebug.com/cert1.pem' in /root/xrdebug/vendor/react/socket/src/SecureServer.php:196
Stack trace:
#0 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Socket\SecureServer->React\Socket\{closure}()
#1 /root/xrdebug/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\RejectedPromise->then()
#2 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#3 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#4 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#5 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Promise\Promise::React\Promise\{closure}()
#6 /root/xrdebug/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\RejectedPromise->then()
#7 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#8 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#9 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#10 /root/xrdebug/vendor/react/promise/src/Deferred.php(50): React\Promise\Promise::React\Promise\{closure}()
#11 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(151): React\Promise\Deferred->reject()
#12 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(85): React\Socket\StreamEncryption->toggleCrypto()
#13 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Socket\StreamEncryption->React\Socket\{closure}()
#14 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#15 /root/xrdebug/xrdebug(223): React\EventLoop\StreamSelectLoop->run()
#16 {main}
```

```plain
RuntimeException: Connection from tcp://172.71.238.114:31732 failed during TLS handshake: Unable to set private key file `/etc/letsencrypt/archive/merge.xrdebug.com/chain1.pem' in /root/xrdebug/vendor/react/socket/src/SecureServer.php:196
Stack trace:
#0 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Socket\SecureServer->React\Socket\{closure}()
#1 /root/xrdebug/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\RejectedPromise->then()
#2 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#3 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#4 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#5 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Promise\Promise::React\Promise\{closure}()
#6 /root/xrdebug/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\RejectedPromise->then()
#7 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#8 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#9 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#10 /root/xrdebug/vendor/react/promise/src/Deferred.php(50): React\Promise\Promise::React\Promise\{closure}()
#11 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(151): React\Promise\Deferred->reject()
#12 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(85): React\Socket\StreamEncryption->toggleCrypto()
#13 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Socket\StreamEncryption->React\Socket\{closure}()
#14 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#15 /root/xrdebug/xrdebug(223): React\EventLoop\StreamSelectLoop->run()
#16 {main}
```

```plain
untimeException: Connection from tcp://172.71.238.114:40420 failed during TLS handshake: Unable to set private key file `/etc/letsencrypt/archive/merge.xrdebug.com/fullchain1.pem' in /root/xrdebug/vendor/react/socket/src/SecureServer.php:196
Stack trace:
#0 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Socket\SecureServer->React\Socket\{closure}()
#1 /root/xrdebug/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\RejectedPromise->then()
#2 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#3 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#4 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#5 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Promise\Promise::React\Promise\{closure}()
#6 /root/xrdebug/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\RejectedPromise->then()
#7 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#8 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#9 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#10 /root/xrdebug/vendor/react/promise/src/Deferred.php(50): React\Promise\Promise::React\Promise\{closure}()
#11 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(151): React\Promise\Deferred->reject()
#12 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(85): React\Socket\StreamEncryption->toggleCrypto()
#13 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Socket\StreamEncryption->React\Socket\{closure}()
#14 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#15 /root/xrdebug/xrdebug(223): React\EventLoop\StreamSelectLoop->run()
#16 {main}
```

```plain
RuntimeException: Connection from tcp://172.71.238.115:29108 failed during TLS handshake: Unable to set local cert chain file `/etc/letsencrypt/live/merge.xrdebug.com/privkey.pem'; Check that your cafile/capath settings include details of your certificate and its issuer in /root/xrdebug/vendor/react/socket/src/SecureServer.php:196
Stack trace:
#0 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Socket\SecureServer->React\Socket\{closure}()
#1 /root/xrdebug/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\RejectedPromise->then()
#2 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#3 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#4 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#5 /root/xrdebug/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Promise\Promise::React\Promise\{closure}()
#6 /root/xrdebug/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\RejectedPromise->then()
#7 /root/xrdebug/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}()
#8 /root/xrdebug/vendor/react/promise/src/Promise.php(192): React\Promise\Promise->settle()
#9 /root/xrdebug/vendor/react/promise/src/Promise.php(292): React\Promise\Promise->reject()
#10 /root/xrdebug/vendor/react/promise/src/Deferred.php(50): React\Promise\Promise::React\Promise\{closure}()
#11 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(151): React\Promise\Deferred->reject()
#12 /root/xrdebug/vendor/react/socket/src/StreamEncryption.php(85): React\Socket\StreamEncryption->toggleCrypto()
#13 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Socket\StreamEncryption->React\Socket\{closure}()
#14 /root/xrdebug/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#15 /root/xrdebug/xrdebug(223): React\EventLoop\StreamSelectLoop->run()
#16 {main}
```

**Comment by rodber** [comment]
Need to fix the context, here:

```sh
./xrdebug -p 443 -c /etc/letsencrypt/live/merge.xrdebug.com/fullchain.pem -z /etc/letsencrypt/live/merge.xrdebug.com/privkey.pem
```

By passing "z" for the private key the HTTPS context now works.

```php
        'tls' => [
            'local_cert' => $cert,
            'local_pk' => $certPk,
        ],
```
